## Slicing en Numpy

Para este cuatrimestre, el objetivo es poder usar el poder de algunas de las funcionalidades internas que trae la librería Numpy, que hacen más rápido el cálculo de las operaciones más básicas del álgebra lineal (sumas y multiplicaciones de matrices y vectores).

Si quieren conocer más sobre el tema, la necesidad de hacer álgebra lineal numérica rápida viene desde hace una buena cantidad de tiempo y LA librería por excelencia para hacer eso es [BLAS](http://www.netlib.org/blas/). Numpy provee su implementación de las funciones de esta librería, descargándola de forma automática cuando es instalada.

Si queremos aprovechar el poder de estas librerías, es necesario reducir la cantidad de bucles que usamos en nuestros cálculos y comenzar a realizar operaciones en bloques o rebanadas de matrices y vectores.

In [1]:
# Como siempre, importemos la librería y definamos algunos elementos de ejemplo
import numpy as np
# Recordemos agregar el dtype si vamos a trabajar con flotantes
matriz = np.array(range(36), dtype=float).reshape((6, 6))
vector = np.array(range(6), dtype=float)

print("matriz = \n", matriz)
print("vector = \n", vector)

matriz = 
 [[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]
vector = 
 [0. 1. 2. 3. 4. 5.]


In [2]:
# Obtener todos los elementos del vector HASTA (sin contar a) N
N = 4
print(vector[:N])

[0. 1. 2. 3.]


In [3]:
# Obtener todos los elementos del vector DESDE N
print(vector[N:])

[4. 5.]


In [4]:
# Obtener todos los elementos del vector DESDE M HASTA (sin contar a) N
M = 2
print(vector[M:N])

[2. 3.]


In [5]:
# Es posible usar índices negativos, lo cual puede ser de utilidad en algunos casos.
# Por ejemplo si queremos llegar al anteúltimo elemento usamos '-1'
print(vector[:-1])

[0. 1. 2. 3. 4.]


In [6]:
# Obtener los elementos del vector al revés, o una parte al revés
# El primer ':' separa entre principio y fin, el segundo ':' indica cómo avanzar
print(vector[::-1])
print(vector[N:M:-1])

[5. 4. 3. 2. 1. 0.]
[4. 3.]


In [7]:
# Podemos obtener los elementos de acuerdo a un índice que definamos como una lista de Python
indice = [2, 0, 3, 4]
print(vector[indice])

[2. 0. 3. 4.]


In [8]:
# Podemos hacer lo mismo con matrices, tomando pedazos a través de cualquiera de sus ejes [filas, columnas].
# Recuerden que un índice desde 0 hasta 0 no nos va a dar un array vacío.
for idx in range(7):
    print("matriz hasta {}".format(idx))
    print(matriz[:idx, :idx])

matriz hasta 0
[]
matriz hasta 1
[[0.]]
matriz hasta 2
[[0. 1.]
 [6. 7.]]
matriz hasta 3
[[ 0.  1.  2.]
 [ 6.  7.  8.]
 [12. 13. 14.]]
matriz hasta 4
[[ 0.  1.  2.  3.]
 [ 6.  7.  8.  9.]
 [12. 13. 14. 15.]
 [18. 19. 20. 21.]]
matriz hasta 5
[[ 0.  1.  2.  3.  4.]
 [ 6.  7.  8.  9. 10.]
 [12. 13. 14. 15. 16.]
 [18. 19. 20. 21. 22.]
 [24. 25. 26. 27. 28.]]
matriz hasta 6
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]


In [9]:
# La columna i-ésima de una matriz se consigue sin tocar la primera dimensión (usando ':')
print(matriz[:, 3])
# NOTAR: Esto nos da un array de Numpy de una dimensión, no genera uno de dos dimensiones con sólo una columna.

[ 3.  9. 15. 21. 27. 33.]


In [10]:
# Nuevamente, podemos usar índices para todos lados y combinarlos
indice_filas = [2, 4]
print(matriz[np.array(indice_filas), :4])

[[12. 13. 14. 15.]
 [24. 25. 26. 27.]]


## Operaciones
Veamos por qué es tan útil trabajar con las operaciones que vienen en las librerías de Numpy.

Definamos una matriz bastante grande formada por números aleatorios con una distribución normal (esta matriz es inversible con probabilidad 1, por qué?). Vamos a definir también un vector al que podamos multiplicar por ella.

In [11]:
import time
# Si se pone muy pesada la máquina, pueden achicar un poco el número
big_N = 10000
big_matrix = np.random.random((big_N, big_N))
big_vector = np.random.random(big_N)

In [12]:
# Hagamos la multiplicación matriz - vector a manopla y veamos cuánto tiempo toma (vayan a armar el mate o algo...)
# Generamos un vector vacío
resultado = np.empty(big_N)
start = time.time()
for fila in range(big_N):
    resultado[fila] = 0.0
    for columna in range(big_N):
        resultado[fila] += big_matrix[fila, columna] * big_vector[columna];

end = time.time()
print("La operación tomó {} segundos".format(end - start))

La operación tomó 94.61298394203186 segundos


In [13]:
# Qué pasa cuando lo hacemos usando @?
resultado = np.empty(big_N)
start = time.time()
resultado = big_matrix @ big_vector
end = time.time()
print("La operación tomó {} segundos".format(end - start))

La operación tomó 0.09396958351135254 segundos


In [ ]:
# Quieren probar cuánto toma el producto matriz-matriz? Pueden ejecutar abajo, va a tardar demasiado tiempo
# (lo que haya tardado la versión anterior multiplicado por big_N...)
resultado = np.empty((big_N, big_N))
start = time.time()
for fila in range(big_N):
    for columna in range(big_N):
        resultado[fila, columna] = 0.0
        for idx in range(big_N):
                resultado[fila, columna] += big_matrix[fila, idx] * big_matrix[idx, columna]
end = time.time()
print("La operación tomó {} segundos".format(end - start))

In [16]:
start = time.time()
resultado = big_matrix @ big_matrix
end = time.time()
print("La operación tomó {} segundos".format(end - start))

La operación tomó 25.925135135650635 segundos


## Solución de sistemas lineales
Resolvamos un sistema triangular inferior también, usemos la función de Numérico I y luego slicing.

In [17]:
def sol_trinf(A, b):
    n = A.shape[0]
    x = b.copy()
    
    for idx in range(n):
        for jdx in range(idx):
            x[idx] = x[idx] - A[idx, jdx] * x[jdx]
        x[idx] = x[idx] / A[idx, idx]

    return x

In [18]:
big_N = 50
# Generamos una matriz random y la hacemos triangular inferior
big_matrix = np.tril(np.random.random((big_N, big_N)))
big_vector = np.random.random(big_N)
start = time.time()
x = sol_trinf(big_matrix, big_vector)
end = time.time()
print("La operación tomó {} segundos".format(end - start))
print("Estamos cerca de la solución? Norma de la resta: {}".format(np.linalg.norm(big_matrix @ x - big_vector)))

La operación tomó 0.0017025470733642578 segundos
Estamos cerca de la solución? Norma de la resta: 2.0905772038047244e-07


In [19]:
# Probemos con slicing
def sol_trinffil(A, b):
    n = len(b)
    x = b.copy()
    for i in range(n):
        x[i] = (b[i] - A[i, :i]@x[:i])/A[i,i]
    return x

In [20]:
big_matrix = np.tril(np.random.random((big_N, big_N)))
big_vector = np.random.random(big_N)
start = time.time()
x = sol_trinffil(big_matrix, big_vector)
end = time.time()
print("La operación tomó {} segundos".format(end - start))
print("Estamos cerca de la solución? Norma de la resta: {}".format(np.linalg.norm(big_matrix @ x - big_vector)))

La operación tomó 0.0008084774017333984 segundos
Estamos cerca de la solución? Norma de la resta: 8.385577118411968e-08


## Usando Numpy para contrastar
Vamos a empezar a usar pedazos de matrices y vectores para hacer algunas de las operaciones.
Lo bueno es que Numpy ya tiene su propia implementación de todos los métodos que vamos a usar este cuatrimestre, como las descomposiciones de Cholesky, LU o QR (Documentación en https://numpy.org/doc/stable/reference/routines.linalg.html). Podremos contrastar nuestro resultado con lo que dé ahí (no pretendan que nuestras funciones tarden menos que las de Numpy, porque usan [LAPACK](http://www.netlib.org/lapack/))